"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from langchain_core.callbacks import AsyncCallbackManager, CallbackManager, Callbacks
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import CheckpointMetadata

def patch_configurable(
    config: Optional[RunnableConfig], patch: dict[str, Any]
) -> RunnableConfig: ...
def patch_checkpoint_map(
    config: Optional[RunnableConfig], metadata: Optional[CheckpointMetadata]
) -> RunnableConfig: ...
def merge_configs(*configs: Optional[RunnableConfig]) -> RunnableConfig:
    """Merge multiple configs into one.

    Args:
        *configs (Optional[RunnableConfig]): The configs to merge.

    Returns:
        RunnableConfig: The merged config.
    """
    ...

def patch_config(
    config: Optional[RunnableConfig],
    *,
    callbacks: Optional[Callbacks] = ...,
    recursion_limit: Optional[int] = ...,
    max_concurrency: Optional[int] = ...,
    run_name: Optional[str] = ...,
    configurable: Optional[dict[str, Any]] = ...,
) -> RunnableConfig:
    """Patch a config with new values.

    Args:
        config (Optional[RunnableConfig]): The config to patch.
        callbacks (Optional[BaseCallbackManager], optional): The callbacks to set.
          Defaults to None.
        recursion_limit (Optional[int], optional): The recursion limit to set.
          Defaults to None.
        max_concurrency (Optional[int], optional): The max concurrency to set.
          Defaults to None.
        run_name (Optional[str], optional): The run name to set. Defaults to None.
        configurable (Optional[Dict[str, Any]], optional): The configurable to set.
          Defaults to None.

    Returns:
        RunnableConfig: The patched config.
    """
    ...

def get_callback_manager_for_config(
    config: RunnableConfig, tags: Optional[Sequence[str]] = ...
) -> CallbackManager:
    """Get a callback manager for a config.

    Args:
        config (RunnableConfig): The config.

    Returns:
        CallbackManager: The callback manager.
    """
    ...

def get_async_callback_manager_for_config(
    config: RunnableConfig, tags: Optional[Sequence[str]] = ...
) -> AsyncCallbackManager:
    """Get an async callback manager for a config.

    Args:
        config (RunnableConfig): The config.

    Returns:
        AsyncCallbackManager: The async callback manager.
    """
    ...

def ensure_config(*configs: Optional[RunnableConfig]) -> RunnableConfig:
    """Ensure that a config is a dict with all keys present.

    Args:
        config (Optional[RunnableConfig], optional): The config to ensure.
          Defaults to None.

    Returns:
        RunnableConfig: The ensured config.
    """
    ...

def get_configurable() -> dict[str, Any]: ...
