"""This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures

type AnyFuture = asyncio.Future | concurrent.futures.Future

def chain_future(source: AnyFuture, destination: concurrent.futures.Future) -> None: ...
