"""add_other_to_searchdatabasesource_enum

Revision ID: 1e530067ad44
Revises: ec76fb98d0da
Create Date: 2025-05-20 05:37:52.914046+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from loguru import logger

# revision identifiers, used by Alembic.
revision: str = "1e530067ad44"
down_revision: str | None = "ec76fb98d0da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE searchdatabasesource_enum ADD VALUE IF NOT EXISTS 'Other';")
    op.execute("ALTER TYPE searchdatabasesource_enum ADD VALUE IF NOT EXISTS 'Embase';")
    op.execute(
        "ALTER TYPE searchdatabasesource_enum ADD VALUE IF NOT EXISTS 'benchmark_csv';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removing enum values can be problematic if data using them exists.
    # Consider the implications carefully. For this example, we'll assume it's safe or handled.
    # op.execute("ALTER TYPE searchdatabasesource_enum DROP VALUE 'Other';") # This is illustrative; direct drop is complex
    # op.execute("ALTER TYPE searchdatabasesource_enum DROP VALUE 'Embase';")
    # op.execute("ALTER TYPE searchdatabasesource_enum DROP VALUE 'benchmark_csv';")
    # PostgreSQL does not directly support DROP VALUE from an enum easily.
    # Downgrading typically involves creating a new enum without the value,
    # updating tables, dropping the old enum, and renaming the new one.
    # For simplicity in this context, we'll leave the downgrade as a no-op or a comment.
    logger.warning(
        "Downgrading enum values like 'Other', 'Embase', 'benchmark_csv' from searchdatabasesource_enum is a complex operation and not automatically handled here. Manual review and steps are required if a true rollback of this change is needed."
    )
    # ### end Alembic commands ###
