"""add uuid test table

Revision ID: 254fe6c3d36d
Revises:
Create Date: 2025-01-21 22:18:21.067563+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "254fe6c3d36d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uuid_test",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uuid_test")
    # ### end Alembic commands ###
