"""fix logrecord indexes

Revision ID: 2c7373437db5
Revises: 8f3511ee9250
Create Date: 2025-02-16 18:27:11.661477+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2c7373437db5"
down_revision: Union[str, None] = "8f3511ee9250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_log_records_message", table_name="log_records")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_log_records_message", "log_records", ["message"], unique=False)
    # ### end Alembic commands ###
