"""Add screening_resolutions table and resolution_id fk

Revision ID: 308659b7dfb8
Revises: c5df8da2885b
Create Date: 2025-04-04 21:26:04.581153+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '308659b7dfb8'
down_revision: Union[str, None] = 'c5df8da2885b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
