"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Type, TypeVar

class LangGraphDeprecationWarning(DeprecationWarning): ...

F = TypeVar("F", bound=Callable[..., Any])
C = TypeVar("C", bound=Type[Any])

def deprecated(
    since: str, alternative: str, *, removal: str = ..., example: str = ...
) -> Callable[[F], F]: ...
def deprecated_parameter(
    arg_name: str, since: str, alternative: str, *, removal: str
) -> Callable[[F], F]: ...
