"""This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any, Generic, Self

from langgraph.channels.base import BaseChannel, Value

class EphemeralValue(Generic[Value], BaseChannel[Value, Value, Value]):
    """Stores the value received in the step immediately preceding, clears after."""

    __slots__ = ...
    def __init__(self, typ: Any, guard: bool = ...) -> None: ...
    def __eq__(self, value: object) -> bool: ...
    @property
    def ValueType(self) -> type[Value]:
        """The type of the value stored in the channel."""

    @property
    def UpdateType(self) -> type[Value]:
        """The type of the update received by the channel."""

    def from_checkpoint(self, checkpoint: Value | None) -> Self: ...
    def update(self, values: Sequence[Value]) -> bool: ...
    def get(self) -> Value: ...
