classDiagram
    class PubmedArticleSet
    PubmedArticleSet --> PubmedArticle
    PubmedArticleSet --> PubmedBookArticle
    class BookDocumentSet
    BookDocumentSet --> "*" BookDocument
    BookDocumentSet --> DeleteDocument
    class PubmedBookArticleSet
    PubmedBookArticleSet --> "*" PubmedBookArticle
    class PubmedArticle
    PubmedArticle --> MedlineCitation
    PubmedArticle --> PubmedData
    class PubmedBookArticle
    PubmedBookArticle --> BookDocument
    PubmedBookArticle --> PubmedBookData
    class BookDocument
    BookDocument --> PMID
    BookDocument --> ArticleIdList
    BookDocument --> Book
    BookDocument --> "*" LocationLabel
    BookDocument --> ArticleTitle
    BookDocument --> VernacularTitle
    BookDocument --> Pagination
    BookDocument --> "*" Language
    BookDocument --> "*" AuthorList
    BookDocument --> InvestigatorList
    BookDocument --> "*" PublicationType
    BookDocument --> Abstract
    BookDocument --> Sections
    BookDocument --> "*" KeywordList
    BookDocument --> ContributionDate
    BookDocument --> DateRevised
    BookDocument --> GrantList
    BookDocument --> "*" ItemList
    BookDocument --> "*" ReferenceList
    class DeleteCitation
    DeleteCitation --> "*" PMID
    class DeleteDocument
    DeleteDocument --> "*" PMID
    class MedlineCitation
    MedlineCitation --> PMID
    MedlineCitation --> DateCompleted
    MedlineCitation --> DateRevised
    MedlineCitation --> Article
    MedlineCitation --> MedlineJournalInfo
    MedlineCitation --> ChemicalList
    MedlineCitation --> SupplMeshList
    MedlineCitation --> "*" CitationSubset
    MedlineCitation --> CommentsCorrectionsList
    MedlineCitation --> GeneSymbolList
    MedlineCitation --> MeshHeadingList
    MedlineCitation --> NumberOfReferences
    MedlineCitation --> PersonalNameSubjectList
    MedlineCitation --> "*" OtherID
    MedlineCitation --> "*" OtherAbstract
    MedlineCitation --> "*" KeywordList
    MedlineCitation --> CoiStatement
    MedlineCitation --> "*" SpaceFlightMission
    MedlineCitation --> "*" InvestigatorList
    MedlineCitation --> "*" GeneralNote
    class PubmedData
    PubmedData --> History
    PubmedData --> PublicationStatus
    PubmedData --> ArticleIdList
    PubmedData --> ObjectList
    PubmedData --> "*" ReferenceList
    class PubmedBookData
    PubmedBookData --> History
    PubmedBookData --> PublicationStatus
    PubmedBookData --> ArticleIdList
    PubmedBookData --> ObjectList
    class Article
    Article --> Journal
    Article --> "*" ELocationID
    class Abstract
    Abstract --> "*" AbstractText
    Abstract --> CopyrightInformation
    class AbstractText
    AbstractText --> mml
    AbstractText --> DispFormula
    class AccessionNumber
    class AccessionNumberList
    AccessionNumberList --> "*" AccessionNumber
    class Acronym
    class Affiliation
    class AffiliationInfo
    AffiliationInfo --> Affiliation
    AffiliationInfo --> "*" Identifier
    class Agency
    class ArticleDate
    ArticleDate --> Year
    ArticleDate --> Month
    ArticleDate --> Day
    class ArticleId
    class ArticleIdList
    ArticleIdList --> "*" ArticleId
    class ArticleTitle
    ArticleTitle --> mml
    class Author
    Author --> LastName
    Author --> CollectiveName
    class AuthorList
    AuthorList --> "*" Author
    class b
    class BeginningDate
    BeginningDate --> Year
    BeginningDate --> Season
    class Book
    Book --> Publisher
    Book --> BookTitle
    Book --> PubDate
    Book --> BeginningDate
    Book --> EndingDate
    Book --> "*" AuthorList
    Book --> InvestigatorList
    Book --> Volume
    Book --> VolumeTitle
    Book --> Edition
    Book --> CollectionTitle
    Book --> "*" Isbn
    Book --> "*" ELocationID
    Book --> Medium
    Book --> ReportNumber
    class BookTitle
    BookTitle --> mml
    class Chemical
    Chemical --> RegistryNumber
    Chemical --> NameOfSubstance
    class ChemicalList
    ChemicalList --> "*" Chemical
    class Citation
    Citation --> mml
    class CitationSubset
    class CoiStatement
    class CollectionTitle
    CollectionTitle --> mml
    class CollectiveName
    class CommentsCorrections
    CommentsCorrections --> RefSource
    CommentsCorrections --> PMID
    CommentsCorrections --> Note
    class CommentsCorrectionsList
    CommentsCorrectionsList --> "*" CommentsCorrections
    class ContractNumber
    class ContributionDate
    ContributionDate --> Year
    ContributionDate --> Season
    class CopyrightInformation
    class Country
    class DataBank
    DataBank --> DataBankName
    DataBank --> AccessionNumberList
    class DataBankList
    DataBankList --> "*" DataBank
    class DataBankName
    class DateCompleted
    DateCompleted --> Year
    DateCompleted --> Month
    DateCompleted --> Day
    class DateRevised
    DateRevised --> Year
    DateRevised --> Month
    DateRevised --> Day
    class Day
    class DescriptorName
    class DispFormula
    DispFormula --> mml
    class Edition
    class ELocationID
    class EndingDate
    EndingDate --> Year
    EndingDate --> Season
    class EndPage
    class ForeName
    class GeneSymbol
    class GeneSymbolList
    GeneSymbolList --> "*" GeneSymbol
    class GeneralNote
    class Grant
    Grant --> GrantID
    Grant --> Acronym
    Grant --> Agency
    Grant --> Country
    class GrantID
    class GrantList
    GrantList --> "*" Grant
    class History
    History --> "*" PubMedPubDate
    class Hour
    class i
    class Identifier
    class Initials
    class Investigator
    Investigator --> LastName
    Investigator --> ForeName
    Investigator --> Initials
    Investigator --> Suffix
    Investigator --> "*" Identifier
    Investigator --> "*" AffiliationInfo
    class InvestigatorList
    InvestigatorList --> "*" Investigator
    class Isbn
    class ISOAbbreviation
    class ISSN
    class ISSNLinking
    class Issue
    class Item
    class ItemList
    ItemList --> "*" Item
    class Journal
    Journal --> ISSN
    Journal --> JournalIssue
    Journal --> Title
    Journal --> ISOAbbreviation
    class JournalIssue
    JournalIssue --> Volume
    JournalIssue --> Issue
    JournalIssue --> PubDate
    class Keyword
    Keyword --> mml
    class KeywordList
    KeywordList --> "*" Keyword
    class Language
    class LastName
    class LocationLabel
    class Medium
    class MedlineDate
    class MedlineJournalInfo
    MedlineJournalInfo --> Country
    MedlineJournalInfo --> MedlineTA
    MedlineJournalInfo --> NlmUniqueID
    MedlineJournalInfo --> ISSNLinking
    class MedlinePgn
    class MedlineTA
    class MeshHeading
    MeshHeading --> DescriptorName
    MeshHeading --> "*" QualifierName
    class MeshHeadingList
    MeshHeadingList --> "*" MeshHeading
    class Minute
    class Month
    class NameOfSubstance
    class NlmUniqueID
    class Note
    class NumberOfReferences
    class Object
    Object --> "*" Param
    class ObjectList
    ObjectList --> "*" Object
    class OtherAbstract
    OtherAbstract --> "*" AbstractText
    OtherAbstract --> CopyrightInformation
    class OtherID
    class PMID
    class Pagination
    Pagination --> StartPage
    Pagination --> MedlinePgn
    class Param
    class PersonalNameSubject
    PersonalNameSubject --> LastName
    PersonalNameSubject --> ForeName
    PersonalNameSubject --> Initials
    PersonalNameSubject --> Suffix
    class PersonalNameSubjectList
    PersonalNameSubjectList --> "*" PersonalNameSubject
    class PubDate
    PubDate --> Year
    PubDate --> Season
    PubDate --> MedlineDate
    class PublicationStatus
    class PublicationType
    class PublicationTypeList
    PublicationTypeList --> "*" PublicationType
    class PubMedPubDate
    PubMedPubDate --> Year
    PubMedPubDate --> Month
    PubMedPubDate --> Day
    PubMedPubDate --> Second
    class Publisher
    Publisher --> PublisherName
    Publisher --> PublisherLocation
    class PublisherLocation
    class PublisherName
    class QualifierName
    class Reference
    Reference --> Citation
    Reference --> ArticleIdList
    class ReferenceList
    ReferenceList --> Title
    ReferenceList --> "*" Reference
    ReferenceList --> "*" ReferenceList
    class RefSource
    class RegistryNumber
    class ReportNumber
    class Season
    class Second
    class Section
    Section --> LocationLabel
    Section --> SectionTitle
    Section --> "*" Section
    class Sections
    Sections --> "*" Section
    class SectionTitle
    class SpaceFlightMission
    class StartPage
    class sub
    class Suffix
    class sup
    class SupplMeshList
    SupplMeshList --> "*" SupplMeshName
    class SupplMeshName
    class Title
    class u
    class URL
    class VernacularTitle
    VernacularTitle --> mml
    class Volume
    class VolumeTitle
    class Year
