"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable
from langgraph.utils.runnable import RunnableSeq

def get_runnable_for_func(func: Callable[..., Any]) -> RunnableSeq: ...

CACHE: dict[Callable[..., Any], RunnableSeq] = ...
