"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from langgraph.types import PregelExecutableTask, RetryPolicy

logger = ...
SUPPORTS_EXC_NOTES = ...

def run_with_retry(
    task: PregelExecutableTask,
    retry_policy: Optional[RetryPolicy],
    configurable: Optional[dict[str, Any]] = ...,
) -> None:
    """Run a task with retries."""
    ...

async def arun_with_retry(
    task: PregelExecutableTask,
    retry_policy: Optional[RetryPolicy],
    stream: bool = ...,
    configurable: Optional[dict[str, Any]] = ...,
) -> None:
    """Run a task asynchronously with retries."""
    ...
