"""
This type stub file was generated by pyright.
"""

from typing import Optional
from langgraph.checkpoint.base import ChannelVersions
from langgraph.utils.runnable import Runnable

def get_new_channel_versions(
    previous_versions: ChannelVersions, current_versions: ChannelVersions
) -> ChannelVersions:
    """Get subset of current_versions that are newer than previous_versions."""
    ...

def find_subgraph_pregel(candidate: Runnable) -> Optional[Runnable]: ...
