"""
This type stub file was generated by pyright.
"""

from typing import Any, Mapping, Optional, Sequence, Union
from langgraph.channels.base import BaseChannel
from langgraph.pregel.read import PregelNode
from langgraph.types import All

def validate_graph(
    nodes: Mapping[str, PregelNode],
    channels: dict[str, BaseChannel],
    input_channels: Union[str, Sequence[str]],
    output_channels: Union[str, Sequence[str]],
    stream_channels: Optional[Union[str, Sequence[str]]],
    interrupt_after_nodes: Union[All, Sequence[str]],
    interrupt_before_nodes: Union[All, Sequence[str]],
) -> None: ...
def validate_keys(
    keys: Optional[Union[str, Sequence[str]]], channels: Mapping[str, Any]
) -> None: ...
