name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *" # Run daily at 01:30

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          stale-pr-message: "This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"
